# Generated by Django 4.2.3 on 2023-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.CharField(max_length=500),
        ),
    ]
